// Code generated by protoc-gen-go.
// source: lazybug.proto
// DO NOT EDIT!

/*
Package lazybug is a generated protocol buffer package.

It is generated from these files:
	lazybug.proto

It has these top-level messages:
	FeedbackAddRequest
*/
package lazybug

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FeedbackAddRequest struct {
	Identifier   string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	CreationDate string `protobuf:"bytes,2,opt,name=creationDate" json:"creationDate,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Meta         []byte `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Snapshot     []byte `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (m *FeedbackAddRequest) Reset()                    { *m = FeedbackAddRequest{} }
func (m *FeedbackAddRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedbackAddRequest) ProtoMessage()               {}
func (*FeedbackAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FeedbackAddRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *FeedbackAddRequest) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *FeedbackAddRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FeedbackAddRequest) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *FeedbackAddRequest) GetSnapshot() []byte {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func init() {
	proto.RegisterType((*FeedbackAddRequest)(nil), "lazybug.FeedbackAddRequest")
}

func init() { proto.RegisterFile("lazybug.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x31, 0x0e, 0x82, 0x40,
	0x10, 0x45, 0xb3, 0x8a, 0xa2, 0x13, 0x6c, 0xa6, 0x9a, 0x58, 0x18, 0x42, 0x45, 0x65, 0xe3, 0x09,
	0x4c, 0x8c, 0x07, 0xe0, 0x06, 0x03, 0x3b, 0xea, 0x46, 0xdd, 0x45, 0x18, 0x0a, 0x3d, 0x8e, 0x27,
	0x35, 0xd9, 0xa8, 0xd1, 0xee, 0xbf, 0xf7, 0x7f, 0xf1, 0x61, 0x71, 0xe1, 0xc7, 0xbd, 0x1e, 0x8e,
	0xeb, 0xb6, 0x0b, 0x1a, 0x30, 0x7d, 0x63, 0xf1, 0x34, 0x80, 0x7b, 0x11, 0x5b, 0x73, 0x73, 0xde,
	0x5a, 0x5b, 0xc9, 0x6d, 0x90, 0x5e, 0x71, 0x05, 0xe0, 0xac, 0x78, 0x75, 0x07, 0x27, 0x1d, 0x99,
	0xdc, 0x94, 0xf3, 0xea, 0xc7, 0x60, 0x01, 0x59, 0xd3, 0x09, 0xab, 0x0b, 0x7e, 0xc7, 0x2a, 0x34,
	0x8a, 0x8b, 0x3f, 0x87, 0x04, 0x69, 0x13, 0xbc, 0x8a, 0x57, 0x1a, 0xc7, 0xfa, 0x83, 0x88, 0x90,
	0x5c, 0x45, 0x99, 0x92, 0xdc, 0x94, 0x59, 0x15, 0x33, 0x2e, 0x61, 0xd6, 0x7b, 0x6e, 0xfb, 0x53,
	0x50, 0x9a, 0x44, 0xff, 0xe5, 0x7a, 0x1a, 0x4f, 0x6f, 0x5e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39,
	0x34, 0xee, 0x5e, 0xc5, 0x00, 0x00, 0x00,
}
